/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package traitgen.application.form.shivoni.gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import traitgen.application.form.shivoni.gui.RepairInvoice;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Anne
 */
public class NewService extends javax.swing.JFrame {

    /**
     * Creates new form NewService
     */
    public NewService() {
        initComponents();
        loadServices();
    }
    
    private RepairInvoice repairInvoice;
    
    public void setRepairInvoice(RepairInvoice ri){
        
        this.repairInvoice = ri;
        
    }
    
     private void loadServices(){
        try {
            
            String query = "SELECT * FROM `service`";
            
            List<String> conditions = new ArrayList<>();
            
            if(!jTextField3.getText().isEmpty()){
                conditions.add("`name` LIKE '"+jTextField3.getText()+"%' ");
            }
            
            if(!conditions.isEmpty()){
                query += " WHERE" +String.join(" AND", conditions);
            }
            
            ResultSet rs = MySQL.executeSearch(query);
            
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            
            
            
            while (rs.next()) { 
                
                Vector<String> vector = new Vector<>();
                vector.add(rs.getString("id"));
                vector.add(rs.getString("name"));
                vector.add(rs.getString("price"));
                dtm.addRow(vector);
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Service Add");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(720, 400));

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 337));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Add New Service");
        jPanel1.add(jLabel1);

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Service Name"));
        jPanel1.add(jTextField1);

        jLabel3.setText("Service Price");
        jPanel1.add(jLabel3);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel1.add(jFormattedTextField1);

        jPanel3.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 10, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        jButton1.setText("Add Service");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Update Service");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Remove Service");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Clear All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jPanel3.add(jPanel2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(366, 50));

        jLabel4.setText("Search Service");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jTextField3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Service Name", "Service Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel8.add(jScrollPane2);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = jTextField1.getText();
        String price = jFormattedTextField1.getText();

        if(name.isEmpty()){

            JOptionPane.showMessageDialog(this, "Please Enter Service Name","Warning", JOptionPane.WARNING_MESSAGE);

        }else if (price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type a price ", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (!price.matches(("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$"))) {
            JOptionPane.showMessageDialog(this, "Please type a valid price ", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{

            try {

                ResultSet rs = MySQL.executeSearch("SELECT * FROM `service` WHERE `name`='"+name+"'");

                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Service already exist","Warning", JOptionPane.WARNING_MESSAGE);
                }else{
                    MySQL.executeIUD("INSERT INTO `service` (`name`,`price`) VALUES ('"+name+"','"+price+"') ");
                    loadServices();
                    clearAll();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable2.getSelectedRow();
        String name = jTextField1.getText();
        String price = jFormattedTextField1.getText();
        if(row ==-1){
            JOptionPane.showMessageDialog(this,"Please select a service to update", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            try {

                ResultSet rs = MySQL.executeSearch("SELECT * FROM `service` WHERE `name`='"+name+"' AND `price`='"+price+"'");

                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Please change service charge before update", "Warning", JOptionPane.WARNING_MESSAGE);
                }else{
                    MySQL.executeIUD("UPDATE `service` SET `price`='"+price+"' WHERE `name`='"+name+"' ");
                    loadServices();
                }

            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable2.getSelectedRow();
        String name = jTextField1.getText();

        if(row ==-1){
            JOptionPane.showMessageDialog(this,"Please select a service to remove", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{

            try {
                MySQL.executeIUD("DELETE FROM `service` WHERE `name`='"+name+"'");
                loadServices();
                clearAll();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();

        jTextField1.setText(String.valueOf(jTable2.getValueAt(row, 1)));
        jFormattedTextField1.setText(String.valueOf(jTable2.getValueAt(row, 2)));

        jTextField1.setEditable(false);
        jButton1.setEnabled(false);

        if(evt.getClickCount()==2){
            if(repairInvoice!=null){
                repairInvoice.getjTextField6().setText(String.valueOf(jTable2.getValueAt(row, 0)));
                repairInvoice.getjTextField5().setText(String.valueOf(jTable2.getValueAt(row, 1)));
                repairInvoice.getjFormattedTextField1().setText(String.valueOf(jTable2.getValueAt(row, 2)));
                this.dispose();

            }
        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        loadServices();
    }//GEN-LAST:event_jTextField3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
      private void clearAll() {
       jTextField1.setText("");
       jTextField3.setText("");
       jFormattedTextField1.setText("");
       jTable2.clearSelection();
       jTextField1.setEditable(true);
       jButton1.setEnabled(true);
    }



}
