name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo (master branch)
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master  
          persist-credentials: true
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Generate stats
      - name: Generate stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install requests
          mkdir -p generated_stats  # Create directory
          python scripts/generate_language_stats.py

      # Step 4: Commit files
      - name: Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global pull.rebase true
          git pull origin master  # Sync with remote
          git add generated_stats/langs.svg
          git commit -m "Update language stats"
          git push origin master  # Push to master
