name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo (with auth)
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master
          persist-credentials: true
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Generate stats
      - name: Generate stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install requests
          mkdir -p generated_stats
          python scripts/generate_language_stats.py

      # Step 4: Commit and push (critical fixes)
      - name: Commit files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global pull.rebase true

          # Reset to avoid conflicts
          git reset --hard origin/master

          # Pull latest changes
          git pull origin master

          # Add and commit
          git add generated_stats/langs.svg
          git commit -m "Update language stats"

          # Push using token-based auth
          git push "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" master
