name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Required for git push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install requests
          python scripts/generate_language_stats.py

      - name: Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add generated_stats/langs.svg
          git commit -m "Update language stats"
          git push
